### ISSUE TITLE
Port implementation to rotor

### ISSUE THREAD

**Issue by tailhook** [nbaksalyar/mio-websocket#12]
Hi,

I'm a developer of [rotor](http://github.com/tailhook/rotor). This is a library built on top of mio that tries to make protocols composable.

For example, you may want to listen for websocket messages and when message comes send an HTTP request to a backend. To make this happen you need to integrate two different protocols, a websocket server and a HTTP client library. In other cases, you may want to use Redis or some SQL library. The asynchronous DNS is a simpler example.

I mean I want multiple things to run in _single_ mio event loop so a single OS thread. It's can't be done when you are writing a protocol implementation on top of bare mio.

I'm trying to make this happen in rotor. We already have an HTTP client and server library (and [few others too](http://rotor.readthedocs.org/en/latest/ecosystem.html)). And I'm going to implement websocket support in it too. It would be great if we join the effort.

**Comment by nbaksalyar** [comment]
Thanks, this is a great suggestion!

To give you an idea on what I'm trying to do here, here are a few things to consider:

First, this library's interface is built around message passing, using Rust's `std::sync::mpsc` package. User's code executes in a main thread, and a user is not even aware of the event loop, which is an implementation detail and uses its own separate thread(s).
This approach was recommended by Carl Lerche in this discussion: https://github.com/carllerche/mio/issues/223, so I decided to build this library in that manner, and I'm not sure that it'd be possible to integrate _rotor_ here without significant changes to code.

However, you're right that a user might want to use it along an async HTTP server, SQL library, etc. in an efficient and composable way. I think a reasonable solution here would be to implement _rotor_ support in a separate library that would share code with _mio-websocket_, effectively separating base WebSocket handling code from a front-end.

In fact, that's why I moved some very basic functions (like frames parsing, serialization, etc.) to a base crate that is not commited to a particular implementation, [websocket-essentials](https://github.com/nbaksalyar/rust-websocket-essentials). It's an early-stage development, though, and I believe much more code can be shared by different WS implementations.

> It would be great if we join the effort

So, to conclude, I'm all for it! Let me know what you think about the proposed way of doing it, making _rotor-websocket_ to use parts of _mio-websocket_ that can be shared between async implementations (and I believe they can be shared to a large extent).

Or maybe you have something else in mind?

**Comment by tailhook** [comment]
Well, separate parser implementation is probably a good idea (but not sure whether it worth it, because websocket framing is pretty simple). 

But that means you are going to maintain separate library anyway, and can't run HTTP server and websocket server on the same host/port.

While using `mpsc` looks attractive, it's actually not so much in Rust (comparing to golang for example). Here are reasons on top of my head:
1. You can't wait with a timeout
2. There is no even wait-for-multiple-channels abstraction (in stable rust)
3. You don't get maximum performance you can (and it seems people want it by default when using Rust)

Writing a message-passing interface for a rotor-based library is easy (that's what I'm doing as part of [stator](https://github.com/tailhook/stator)). But not other way around.

Anyway, feel free to close the issue if you don't feel it's useful.

**Comment by nbaksalyar** [comment]
> Writing a message-passing interface for a rotor-based library is easy (that's what I'm doing as part of stator).

Sounds great! I haven't yet researched _stator_ (and the _rotor_ ecosystem, for that matter) in a great detail, and I'll need some time to ponder over this idea.

I'll do some benchmarks, tests, and proof-of-concepts, and get back to you with results later this week.

Thanks!

**Comment by nbaksalyar** [comment]
Sorry for a delayed response - here's what I think:
1. You're totally right that it's better to join efforts and produce a composable library. Now that _hyper_ implements an async mode with _rotor_ it makes even more sense.
2. This particular library will remain as-is strictly for educational purposes (because it was started as a supplementary sample for a series of articles in my blog), and it _won't_ be published to crates.io.
3. That means that soon I'll create a new repo and code base for a rotor-based, composable WebSocket crate, and code from this library can be heavily reused in the new project.

Please let me know your opinion & if you have something to add.

**Comment by tailhook** [comment]
Sounds fine. Also we should somehow integrate it with rotor-http itself (and maybe hyper too if possible), because we almost always want to serve HTTP and Websockets over the same port.

There are a couple of ways to do the integration, I'm not sure I've figured the best one yet. Anyway, feel free to open an issue in rotor-http for that (I'm also fine with adding websockets to rotor-http directly, to avoid much burden on users to write glue code, if you may contribute there).
